name: "ModTest"

on:
  pull_request:
    branches:
      - main
    
jobs:
  modtest:
    uses: HappyPathway/centralized-actions/.github/workflows/modtest.yml@main
    with:
       workspace: github-repos
       github_server: github.com 
       github_org: HappyPathway
       mod_source: repo/github
       branch: ${{ github.head_ref }}
       terraform_version: 1.9.1
    secrets:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
