name: Terraform CI/CD
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  terraform-ci-cd:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"  # Specify your desired version

      - name: Run Terraform Module Release Action
        uses: HappyPathway/terraform-module-release@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          working-directory: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_OWNER: ${{ vars.GH_ORG }}
