name: "Terraform Test and Tag"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    name: "Terraform Test"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_OWNER: ${{ vars.GH_ORG }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~>1.6.0"
          terraform_wrapper: false

      - name: Format Terraform files
        run: terraform fmt -recursive
        id: fmt

      - name: Check for file changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.changes_detected == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: format terraform files"
          
          # For push events on main branch, create a PR instead of pushing directly
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Create a new branch for the formatting changes
            BRANCH_NAME="format-terraform-$(date +%Y%m%d%H%M%S)"
            git checkout -b $BRANCH_NAME
            git push -u origin $BRANCH_NAME
            
            # Create a pull request using the GitHub CLI or API
            gh pr create --title "chore: format terraform files" \
              --body "This PR contains automatic formatting changes from the CI workflow." \
              --head $BRANCH_NAME \
              --base main
          elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.head.repo.fork }}" == "false" ]]; then
            # Only push to the PR branch if it's from the same repository (not a fork)
            git push origin "HEAD:${{ github.event.pull_request.head.ref }}"
          else
            echo "Changes detected but not pushing to a fork PR. Please update your PR with these formatting changes."
          fi
      
      - name: Terraform Init
        id: init
        run: terraform init -backend=false
      
      - name: Terraform Validate
        id: validate
        run: terraform validate
      
      - name: Run Terraform Tests
        id: test
        run: terraform test
        
      - name: Bump version and push tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
